NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.ent1.b2csm-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.ent1.b2csm-cert.pem
    OrganizationalUnitIdentifier: peer
