# B2CSM crypto-config
#
# Multi-organizations setup for BFT-SMaRt
# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: OrderingNodes
    Domain: orderer.b2csm
    Template:
      Count: 4
      Hostname: "{{.Index}}"
  # ---------------------------------------------------------------------------
  # Frontends
  # ---------------------------------------------------------------------------
  - Name: Frontends
    Domain: frontend.b2csm
    Specs:
      - Hostname: 1000
      - Hostname: 2000
      - Hostname: 3000

# ---------------------------------------------------------------------------
# "PeerOrgs" - Organizations for the endorsing/committing peers
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Org1
  # ---------------------------------------------------------------------------
  - Name: Ent1
    Domain: ent1.b2csm
    EnableNodeOUs: true
    Template:
      Count: 4
      # Start: 5
      Hostname: "{{.Index}}.peer"
    # ---------------------------------------------------------------------------
    # "Users"
    # ---------------------------------------------------------------------------
    # Count -> The number of user accounts _in addition_ to Admin
    # ---------------------------------------------------------------------------
    Users:
      Count: 1
  # ---------------------------------------------------------------------------
  # Org2
  # ---------------------------------------------------------------------------
  # - Name: Ent2
  #  Domain: ent2.b2csm
  #  EnableNodeOUs: true
  #  Template:
  #    Count: 2
  #    Hostname: "{{.Index}}.peer"
  #  Users:
  #    Count: 1
